### ISSUE TITLE
Failed to start 'claptto' on Gadget

### ISSUE THREAD

**Issue by utilitydelta** [xtacocorex/gadget-claptto#1]
Hi Robert!

I've tried to get clapto up an running, following your steps. I cloned the repo, then ran build & deploy OK, then on start I got an error:

I:  Starting:
I:    gifserver_f0698b4f-f78b-46bf-aac7-b24d3c00cf3e
I:      - started
I:    claptto_8bcfe3ab-cd33-4fe5-b8d5-706285f0574f
E:    Failed to start 'claptto' on Gadget
W:    Potential causes:
W:    - container was never deployed

So I Putty'd it up and tried it on the CHIP directly:
/ # docker container ls -a
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS               NAMES
a91b2c4ed910        claptto_8bcfe3ab-cd33-4fe5-b8d5-706285f0574f-img     "/bin/sh -c 'echo ..."   12 minutes ago      Created                                 claptto_8bcfe3ab-cd33-4fe5-b8d5-706285f0574f
476b24427617        gifserver_f0698b4f-f78b-46bf-aac7-b24d3c00cf3e-img   "/bin/sh -c 'echo ..."   13 minutes ago      Up 7 minutes                            gifserver_f0698b4f-f78b-46bf-aac7-b24d3c00cf3e

/ # docker start a91b2c4ed910
Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/video0": lstat /dev/video0: no such file or directory
Error: failed to start containers: a91b2c4ed910

Looks like I'm missing video0. What steps am I missing? Building the kernel with video I imagine? :)

Cheers
Tyson

**Comment by xtacocorex** [comment]
You need a USB Camera hooked up that works with the UVC driver.  You also
need a button to enable/disable clapping.

The container tried to run and failed because the camera wasn't there to
pass into the container.

**Comment by utilitydelta** [comment]
I tried a logitech C170 and a C270, both times had no video0. I'm thinking about trying https://github.com/msolters/linux-chip-build-tool or https://github.com/NextThingCo/Gadget-OS to build a new kernel with UVC support.

**Comment by xtacocorex** [comment]
The kernel mods to add the camera is built as part of the gadget workflow,
you can edit the kernel config right from within the gadget cli and add the
camera driver you need.

**Comment by utilitydelta** [comment]
Nope, didn't work. I noticed you have chippro-linux.config in your repo. You must have applied it somehow? I checked the Gadget CLI code. Build does a docker image pull and does some tagging. deploy copies the docker images over to the CHIP Pro. start does a docker start. Nothing about modding the kernel to support UVC based webcams.

**Comment by xtacocorex** [comment]
You need to look at the gadget cli unstable branch code, that is where the
cli releases are being generated from.

The command should be
`gadget edit rootfs kernel`

after that, you'll need to run `gadget build rootfs`

Once that is done, you'll need to flash from the cli `gadget flash`

**Comment by utilitydelta** [comment]
It works!! cheers man :) you saved me hours of work today.
